### ISSUE TITLE
Error: Cannot find module '../node_modules/carta-frontend/package.json'

### ISSUE THREAD

**Issue by toddpfaff** [CARTAvis/carta-node-server#28]
I'm deploying CARTA Server following the instructions at https://github.com/CARTAvis/carta-node-server/blob/dev/README.md.

I'm doing this all as unprivileged user _carta_.  The only thing I've done differently from the instructions is that instead of:
```
npm install -g carta-node-server
```
I did:
```
npm install carta-node-server
```
because I want everything to be installed to the carta users ~/node_modules/ directory rather than in some global directory.

This is what I have now:

```
carta@astro ~]$ which carta-node-server
~/bin/carta-node-server

[carta@astro ~]$ ls -l $(which carta-node-server)
lrwxrwxrwx 1 carta carta 38 Nov  4 18:06 /home/carta/bin/carta-node-server
-> ../node_modules/.bin/carta-node-server*
```
When I attempt to run carta-node-server I get:

```
[carta@astro ~]$ carta-node-server
Checking config file /etc/carta/config.json
Error: Cannot find module '../node_modules/carta-frontend/package.json'
```
Something is looking for ../node_modules/carta-frontend/package.json.  But ".." relative to where?

Does carta-node-server cd to some runtime working directory path at which ../node_modules/ is not being found?

The file node_modules/carta-frontend/package.json *does* exist:

```
[carta@astro ~]$ ls -l ~/node_modules/carta-frontend/package.json
-rw-rw-r-- 1 carta carta 4802 Nov  4 18:04  /home/carta/node_modules/carta-frontend/package.json
```
Thanks,
Todd

**Comment by toddpfaff** [comment]
I did some searching and found in this file:
```
/home/carta/node_modules/carta-node-server/dist/index.js
```
this code that seems to be relevant to my issue:
```
if (config_1.ServerConfig.frontendPath) {
    console.log(chalk.green.bold(`Serving CARTA frontend from ${config_1.ServerConfig.frontendPath}`));
    app.use("/", express.static(config_1.ServerConfig.frontendPath, { setHeaders: staticHeaderHandler }));
}
else {
    const frontendPackage = require("../node_modules/carta-frontend/package.json");
    const frontendVersion = frontendPackage === null || frontendPackage === void 0 ? void 0 : frontendPackage.version;
    console.log(chalk.green.bold(`Serving packaged CARTA frontend (Version ${frontendVersion})`));
    app.use("/", express.static(path.join(__dirname, "../node_modules/carta-frontend/build"), { setHeaders: staticHeaderHandler }));
}
```

which seems to indicate to me that I should be setting a frontendPath in my configuration.  I searched further and found this in config_schema.json:
```
"frontendPath": {
    "description": "Path to the built frontend folder. If no path is provided, the packaged version will be used",
    "type": "string"
},
```
So I added this to my carta-node-server /etc/carta/config.json:
```
"frontendPath": "/home/carta/node_modules/carta-frontend",
```
and that solved this issue.

**Comment by veggiesaurus** [comment]
you should only need to set the frontend path if you're not using the builtin frontend. But if you need to specify the path due to installing carta-node-server locally instead of globally, then I think you should be pointing to the `carta-frontend/build` directory, instead of just `carta-frontend`. This might explain #30 (since the `carta-frontend` folder doesn't have an `index.html`

**Comment by veggiesaurus** [comment]
@toddpfaff if you're concerned about installing node packages globally, I strongly suggest you try out [NVM](https://github.com/nvm-sh/nvm), as this will allow you to install packages globally for a specific user (the packages end up in the user's home directory).

The underlying issue is that node handles local and global package installations slightly differently. Local installations just go straight into your `node_modules` subdirectory, but global installations have a slightly different approach. Modules go in the `lib/node_modules` folder, but the actual executables associated with a package (for example, `carta-node-server`) go in the `bin` directory

**Comment by toddpfaff** [comment]
As @veggiesaurus suggested in #28, pointing frontendPath to carta-frontend/build has solved this issue.

Also, @veggiesaurus, thanks for the advice about [NVM]( https://github.com/nvm-sh/nvm), I will give that a try.
